config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :tickets do
    member do
      post 'process_csv'
      put 'set_status'
    end
    get 'generate_csv_data', on: :collection
    resources :comments
  end
  root 'tickets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ticket

  validates :body, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :description, presence: true

  enum status: { in_progress: 0, completed: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #:lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :tickets
  has_many :comments
  has_many_attached :documents

  enum role: { developer: 0, sprint_master: 1, admin: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @ticket = Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.create(comment_params)
    redirect_to ticket_path(@ticket)
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :user_id)
    end
end

app/controllers/tickets_controller.rb
require 'csv'
class TicketsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.includes(:user, :comments).order('tickets.created_at desc')
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      flash[:notice] = "Ticket created successfully"
      redirect_to tickets_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket updated successfully"
      redirect_to @ticket
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket deleted successfully"
    redirect_to tickets_path, status: :see_other
  end

  def process_csv
    document = current_user.documents.attach(params[:document])
    if document
      FeedTicketWorker.perform_async(current_user.id)
      redirect_to tickets_path, notice: 'Pushed to sidekiq will take some time. Refresh after interval-base on no of Tickets'
    else
      render :index
    end
  end

  def set_status
    @ticket = Ticket.find_by(id: params[:id])
    if params[:remove].present?
      @ticket.in_progress!
    else
      @ticket.completed!
    end
  end

  def generate_csv_data
    columns_caption = ['Id', 'Title', 'Description', 'Status', 'Created At']
    csv_data = CSV.generate(headers: true) do |csv|
      csv << columns_caption
      Ticket.all.find_each do |item|
        csv << [item.id, item.title, item.description, item.status.titlecase, item.created_at.strftime('%Y/%m/%d')]
      end
    end
    current_user.documents.attach(io: StringIO.new(csv_data), filename: 'data.csv', content_type: 'text/csv')
    UserMailer.send_data_as_csv(current_user.id).deliver_now
    redirect_to tickets_path, notice: 'Attchement has been sent to you email'
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :description, :user_id)
  end

  def set_ticket
    @ticket = Ticket.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, :check_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    password = Devise.friendly_token.first(10)
    @user.password = password
    if @user.save
      UserMailer.with(user: @user, password: password).password_email.deliver_later
      flash[:notice] = 'User was successfully created.'
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :role)
  end

  def check_admin
    return if current_user.admin?

    redirect_to root_path, notice: "You don't have access to this page"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def ticket_count(user)
    total_count = user.tickets.count
    total_count.positive? ? total_count : ''
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/comments/_comment.html.erb
 <p>
    <strong>User:</strong>
    <%= comment.user.email %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

app/views/comments/_form.html.erb
<%= form_with model: [ @ticket, @ticket.comments.build ] do |form| %>
  <p>
    <%= form.text_area :body, class: 'form-control' %>
  </p>

   <p>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </p>
  
  <p>
    <%= form.submit 'Add Comment', class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to 'Todo', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarNav">
      <ul class="navbar-nav">
      <% if current_user.blank? %>
        <li class="nav-item">
          <%= link_to 'Login', user_session_path,  class: "nav-link" %>
        </li>
      <% else %><li>
        <li class="nav-item">
          <p class="nav-link"><%= current_user.email.split('@')[0].titlecase %></p>
        </li>
        <li class="nav-item">
          <p class="nav-link"><span class="material-symbols-outlined">notifications</span>
          <span class="notification-counter"><%= ticket_count(current_user)%></span></p>
        </li>
        <li class="nav-item">
          <%= link_to 'Home', root_path,  class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tickets', tickets_path,  class: "nav-link" %>
        </li>
         <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Manage Users', users_path,  class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= button_to 'Logout', destroy_user_session_path, method: :delete,  class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
  </head>

  <body>
   <%= render 'layouts/nav' %>
   <div class='container-fluid'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with model: ticket do |form| %>
  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title, required: true, class: 'form-control' %>
    <% ticket.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description, required: true, class: 'form-control' %><br>
    <% ticket.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :developer %><br>
    <%= form.select :user_id, options_for_select(User.developer.map { |u| [u.email, u.id] }), {required: true, class: 'form-control'}  %>
    <% ticket.errors.full_messages_for(:user_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div >
    <%= form.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tickets/_import_tickets.html.erb
<div style='margin-left: 78%; margin-top: -62px;'>
<%= form_with url: process_csv_ticket_path(tickets), method: :post do |f|%>
	<div >
  <%= f.label :import_tickets %>
<%= f.file_field 'document', class: 'form-control', style: 'width: 80%' %>
	</div><br>
  <div>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/tickets/_status.html.erb
<% if ticket.in_progress? %>
  <%= @ticket.status.titlecase %>
  <%= link_to "Change Status", set_status_ticket_path(ticket.id), method: :put, remote: true, data: {confirm: "Are you sure you want to mark this ticket as Completed?"}, class: "create_btn" %>
<% else %>
  <%= @ticket.status.titlecase %>
  <%= link_to "Change Status", set_status_ticket_path(ticket.id, remove: 1), method: :put, remote: true, data: {confirm: "Are you sure you want mark it as in progress ticket?"}, class: "create_btn" %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Edit Ticket</h1>

<%= render "form", ticket: @ticket %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Tickets</h1>

<br />
<% unless current_user.developer? %>
  <%= link_to "New Ticket", new_ticket_path, class: 'btn btn-primary' %>
  <%= link_to "Export Ticket to CSV", generate_csv_data_tickets_path, class: 'btn btn-primary' %>

  <%= render "import_tickets", tickets: @tickets %>
<% end %>

<br /><br />

<table class="table table-striped">
  <thead>
    <tr>
     <th>ID</th>
      <th>Title</th>
      <th>Description</th>
      <th>Assigned To</th>
      <th>Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
       <td><%= ticket.id %></td>
        <td><%= ticket.title %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.user.email %></td>
        <td><%= ticket.status.titlecase %></td>
        <td><%= link_to 'Show', ticket, class: 'btn btn-primary' %></td>
        <% unless current_user.developer? %>
        <td><%= link_to 'Edit', edit_ticket_path(ticket), class: 'btn btn-primary'  %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render "form", ticket: @ticket %>

app/views/tickets/set_status.js.erb
$("#ticket_status").html('<%=j render "status", ticket: @ticket %>');

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Title:</strong>
<%= @ticket.title %>
</p>

<p>
<strong>Description:</strong>
<%= @ticket.description %>
</p>

<div>
Status:
  <span id="ticket_status">
    <%= render "status", ticket: @ticket %>
  </span>
</div>
<br>
<h4>Comments</h4>
 <%= render @ticket.comments %>

<strong>Add a comment:</strong>
<%= render 'comments/form' %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email, required: true, class: 'form-control' %>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :role %><br>
     <%= form.collection_select(:role, User.roles.map{ |a| [a[0], a[0].titleize] },  :first, :second, { prompt: "Select Role" },:class=>"form-control col-auto") %>
    <% user.errors.full_messages_for(:role).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.submit 'Create User', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Users</h1>

<br />
<%= link_to "New user", new_user_path, class: 'btn btn-primary' %>

<br /><br />

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
         <td><%= user.role.titlecase %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>